### ISSUE TITLE
Potential incompatibility issues with Cytoscape 3.2.1

### ISSUE THREAD

**Issue by ncatlett** [OpenBEL/bel-nav#36]
After installing the kam-nav jar files in the CytoscapeConfiguration folder, I am unable to launch Cytoscape 3.2.1. Cytoscape 3.1.0 will launch.

**Comment by abargnesi** [comment]
BEL Navigator now builds as a single app JAR that can be installed through Cytoscape.

Try again and please reopen if you continue to see the problem.
